#!/usr/bin/bash
#PBS -N 3fastp
#PBS -q normal
#PBS -l nodes=1:ppn=16
#PBS -l walltime=30:00:00
#PBS -k oe
#PBS -j oe
#PBS -o /home/chrisl/microplastics/out/fastp/batch3.txt
#PBS -m abe
#PBS -M u21652938@tuks.co.za

cd /nlustre/users/chrisl/microplastics/data
module load fastp-0.23.2
fastp -i input/rawdata/20082D-07-29_S0_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-29_S0_L001_R2_001.fastq.gz -o fastp/reads/27_R1.fastq.gz -O fastp/reads/27_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/27.html -j fastp/reports/27.json
fastp -i input/rawdata/20082D-07-31_S31_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-31_S31_L001_R2_001.fastq.gz -o fastp/reads/29_R1.fastq.gz -O fastp/reads/29_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/29.html -j fastp/reports/29.json
fastp -i input/rawdata/Blue-lodge-Sed_S4_L001_R1_001.fastq -I input/rawdata/Blue-lodge-Sed_S4_L001_R2_001.fastq -o fastp/reads/56_R1.fastq -O fastp/reads/56_R2.fastq 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/56.html -j fastp/reports/56.json
fastp -i input/rawdata/20082D-07-48_S48_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-48_S48_L001_R2_001.fastq.gz -o fastp/reads/46_R1.fastq.gz -O fastp/reads/46_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/46.html -j fastp/reports/46.json
fastp -i input/rawdata/20082D-07-19_S0_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-19_S0_L001_R2_001.fastq.gz -o fastp/reads/18_R1.fastq.gz -O fastp/reads/18_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/18.html -j fastp/reports/18.json
fastp -i input/rawdata/20082D-07-03_S25_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-03_S25_L001_R2_001.fastq.gz -o fastp/reads/03_R1.fastq.gz -O fastp/reads/03_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/03.html -j fastp/reports/03.json
fastp -i input/rawdata/20082D-07-34_S32_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-34_S32_L001_R2_001.fastq.gz -o fastp/reads/32_R1.fastq.gz -O fastp/reads/32_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/32.html -j fastp/reports/32.json
fastp -i input/rawdata/20082D-07-52_S52_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-52_S52_L001_R2_001.fastq.gz -o fastp/reads/50_R1.fastq.gz -O fastp/reads/50_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/50.html -j fastp/reports/50.json
fastp -i input/rawdata/20082D-07-27_S0_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-27_S0_L001_R2_001.fastq.gz -o fastp/reads/26_R1.fastq.gz -O fastp/reads/26_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/26.html -j fastp/reports/26.json
fastp -i input/rawdata/20082D-07-41_S41_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-41_S41_L001_R2_001.fastq.gz -o fastp/reads/39_R1.fastq.gz -O fastp/reads/39_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/39.html -j fastp/reports/39.json
