#!/usr/bin/bash
#PBS -N 6fastp
#PBS -q normal
#PBS -l nodes=1:ppn=16
#PBS -l walltime=30:00:00
#PBS -k oe
#PBS -j oe
#PBS -o /home/chrisl/microplastics/out/fastp/batch6.txt
#PBS -m abe
#PBS -M u21652938@tuks.co.za

cd /nlustre/users/chrisl/microplastics/data
module load fastp-0.23.2
fastp -i input/rawdata/20082D-07-55_S55_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-55_S55_L001_R2_001.fastq.gz -o fastp/reads/53_R1.fastq.gz -O fastp/reads/53_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/53.html -j fastp/reports/53.json
fastp -i input/rawdata/20082D-07-24_S0_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-24_S0_L001_R2_001.fastq.gz -o fastp/reads/23_R1.fastq.gz -O fastp/reads/23_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/23.html -j fastp/reports/23.json
fastp -i input/rawdata/Security-level_S5_L001_R1_001.fastq -I input/rawdata/Security-level_S5_L001_R2_001.fastq -o fastp/reads/59_R1.fastq -O fastp/reads/59_R2.fastq 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/59.html -j fastp/reports/59.json
fastp -i input/rawdata/20082D-07-04_S35_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-04_S35_L001_R2_001.fastq.gz -o fastp/reads/04_R1.fastq.gz -O fastp/reads/04_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/04.html -j fastp/reports/04.json
fastp -i input/rawdata/20082D-07-11_S4_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-11_S4_L001_R2_001.fastq.gz -o fastp/reads/11_R1.fastq.gz -O fastp/reads/11_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/11.html -j fastp/reports/11.json
fastp -i input/rawdata/20082D-07-15_S15_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-15_S15_L001_R2_001.fastq.gz -o fastp/reads/14_R1.fastq.gz -O fastp/reads/14_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/14.html -j fastp/reports/14.json
fastp -i input/rawdata/20082D-07-32_S22_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-32_S22_L001_R2_001.fastq.gz -o fastp/reads/30_R1.fastq.gz -O fastp/reads/30_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/30.html -j fastp/reports/30.json
fastp -i input/rawdata/20082D-07-30_S0_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-30_S0_L001_R2_001.fastq.gz -o fastp/reads/28_R1.fastq.gz -O fastp/reads/28_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/28.html -j fastp/reports/28.json
fastp -i input/rawdata/20082D-07-14_S0_L001_R1_001.fastq.gz -I input/rawdata/20082D-07-14_S0_L001_R2_001.fastq.gz -o fastp/reads/13_R1.fastq.gz -O fastp/reads/13_R2.fastq.gz 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/13.html -j fastp/reports/13.json
fastp -i input/rawdata/Military-Sed_S2_L001_R1_001.fastq -I input/rawdata/Military-Sed_S2_L001_R2_001.fastq -o fastp/reads/58_R1.fastq -O fastp/reads/58_R2.fastq 					--detect_adapter_for_pe -cpD -w 16 -h fastp/reports/58.html -j fastp/reports/58.json
